### ISSUE TITLE
Marker

### ISSUE THREAD

**Issue by rmartenss4s** [jeffreykemp/jk64-plugin-simplemap#11]
Jeffrey,

It must be that I'm doing something wrong, but I cannot get the marker to show.

Furthermore, I'd like to:
- add some info to the marker
- prevent zooming / clicking etc.

My application is here:
http://dapex50.smart4apex.nl/ords/f?p=132

regards,
Richard

**Comment by jeffreykemp** [comment]
Hi Richard,

The first issue I can see with your map is that somehow you have set the "syncItem" to a lat,long pair (e.g. "36.169,-115.1") whereas this should be an apex item name (e.g. "P1_LAT_LONG") with which the map should be synchronized. You set the value of the item to the lat, long value and the map will pick that up.

This simple map is designed to allow data-entry for a single marker position; to show info on the map I would use the ReportMap plugin instead.

However, if you want to use the SimpleMap you can add a bit of javascript in a Dynamic Action on the mapLoaded event to show an InfoWindow to the marker, e.g.:

```
opt_map.iw = new google.maps.InfoWindow();
opt_map.iw.setOptions({
    content: $v("P2_INFO")
});
opt_map.iw.open(this.data.map, opt_map.marker);

```

I've put a demo up here:

https://apex.oracle.com/pls/apex/f?p=76577:2

**Comment by jeffreykemp** [comment]
To disable zoom, add this code to the mapLoaded event:

`this.data.map.setOptions({draggable: false, zoomControl: false, scrollwheel: false, disableDoubleClickZoom: true});`

**Comment by jeffreykemp** [comment]
To stop the user clicking on the map and changing the marker position, I think I'll need to make a change to the plugin. Stay tuned.

**Comment by jeffreykemp** [comment]
The next release (0.4) will have a "Read-only" attribute which will disable zoom/pan, and stop the user clicking the map and changing the marker position.
