### ISSUE TITLE
Separate attribute to disable zoom/pan

### ISSUE THREAD

**Issue by jeffreykemp** [jeffreykemp/jk64-plugin-simplemap#13]
At the moment, if readonly is set, the zoom and pan features are also disabled.

Instead, have separate attributes which control whether zoom and pan are disabled or not.

**Comment by martenian** [comment]
Hi Jeff,

Is there a way for me to disable to two finger panning on mobile devices and require only one finger to move around the map? The setting is referred to as “greedy” on googles api documentation. Not sure how I would integrate this into your existing code. 

Appreciate your help.

**Comment by jeffreykemp** [comment]
Adding the following attributes:

* Zoom enabled (PL/SQL expression)
* Pan enabled (PL/SQL expression)
* Gesture Handling - select one of the following values:

"cooperative": Scroll events and one-finger touch gestures scroll the page, and do not zoom or pan the map. Two-finger touch gestures pan and zoom the map. Scroll events with a ctrl key or ⌘ key pressed zoom the map. In this mode the map cooperates with the page.
"greedy": All touch gestures and scroll events pan or zoom the map.
"none": The map cannot be panned or zoomed by user gestures.
"auto": (default) Gesture handling is either cooperative or greedy, depending on whether the page is scrollable.

**Comment by jeffreykemp** [comment]
I've added options to implement these features - your feedback will be welcome.

**Comment by martenian** [comment]
Jeff,

This is awesome! Thank you very much for adding that. Works like a charm.

Thanks,

Mike

**Comment by martenian** [comment]
Hi Jeff,

Is this option available with the other plugin as well? I tried to carry over the changes you made to the other package but am not able to get it to work. Appreciate your time!

Thanks,

Mike

**Comment by jeffreykemp** [comment]
Hi Mike, good idea, I'll raise this on the reportmap plugin as well.
