### ISSUE TITLE
Update map on the basis of coordatinates

### ISSUE THREAD

**Issue by Uditn** [jeffreykemp/jk64-plugin-simplemap#14]
Hi Jeffrey can you just tell me how the map will be marked when a user enter he coordinates in the field.

Thank you!

**Comment by jeffreykemp** [comment]
You need to set the **Synchronize with Item** attribute to the name of a text field on the page. When the user enters coordinates into the field, the map should update.

**Comment by Uditn** [comment]
How to do it can you just elaborate?

**Comment by jeffreykemp** [comment]
1. Create a text field item. Give it a name, e.g. P1_COORDS.
2. On the Attributes on your map plugin region, set the attribute **Synchronize with Item** to the name of the item, e.g. P1_COORDS.

**Comment by Uditn** [comment]
![untitled](https://cloud.githubusercontent.com/assets/25974361/23249190/152348e2-f9c9-11e6-974b-13aa2eeb0aaa.png)
Hi Jeffrey,
I have passed the item but still map is not showing the particular destination. Please suggest
Please view attachment

**Comment by jeffreykemp** [comment]
Please build an example on apex.oracle.com and I can take a look.

Thanks

**Comment by Uditn** [comment]
https://apex.oracle.com/pls/apex/f?p=36814:1:12099810551934:::::

APPLICATION ID : 36814
WORKSPACE : TI
user name  : uditn@tiinfotech.com
PASSWORD : [redacted]
Page no : 1

Thank you for your help

Regards

**Comment by jeffreykemp** [comment]
Thanks. It works for me - for example, when I enter coordinates like this:

-32.49123028794758,115.828857421875

It shows a map with "Nambeelup Rd" nearby.

**Comment by Uditn** [comment]
Have you done any modifications on that particular page?
I am working on version 5.0.3 . Is there any file am I missing.

**Comment by Uditn** [comment]
Hi Jeffrey,

It is working now like a charm. Actually, what I did is pass the static id in region,however when I remove the static id it is working perfectly.

Thank you so much for your time and assistance. 
You are doing a great job.
