### ISSUE TITLE
Get Address, Postal Code and Country in separate elements

### ISSUE THREAD

**Issue by vpier** [jeffreykemp/jk64-plugin-simplemap#16]
Hi Jeffrey,

Thanks a lot for this plugin. 

I was wondering if there was any way to have, address, postal code, etc. on separate elements, or if there are any javascript methods I could get them from .

**Comment by jeffreykemp** [comment]
At the moment the plugin just extracts the formatted address string from the first result returned from the geocoder. This is usually the most detailed/exact result, but I throw away the detailed address part data.

I could enhance the plugin to return all the address components, e.g. street number, street name, locality, postcode, etc..

More details: https://developers.google.com/maps/documentation/geocoding/intro#ReverseGeocoding

Thanks for the suggestion.

**Comment by jeffreykemp** [comment]
Adding a new trigger event "address". A dynamic action on this event will get an attribute "result" which is the first result returned by a geocode (if the geocoding is successful and gets a response).

The javascript can get the address components desired and do whatever you want with them, e.g. this puts some of the address components into some items on the page:

```
// first, clear out the page items
$s("P1_STREET_NUMBER","");
$s("P1_ROUTE","");
$s("P1_LOCALITY","");
$s("P1_AREA","");
$s("P1_COUNTRY","");
$s("P1_POSTAL_CODE","");

// get the address components from the result
var components = this.data.result.address_components;

// components is an array of type/name pairs
for (i=0; i<components.length; i++) {
  // note: "type" is itself an array, but usually the first element is useful enough 
  switch (components[i].types[0]) {
  case "street_number" : $s("P1_STREET_NUMBER", components[i].short_name); break;
  case "route" : $s("P1_ROUTE", components[i].short_name); break;
  case "locality" : $s("P1_LOCALITY", components[i].short_name); break;
  case "administrative_area_level_1" : $s("P1_AREA", components[i].short_name); break;
  case "country" : $s("P1_COUNTRY", components[i].short_name); break;
  case "postal_code" : $s("P1_POSTAL_CODE", components[i].short_name); break;
  }
}
```
