### ISSUE TITLE
Insufficient results found Alert on Dynamic Actions address

### ISSUE THREAD

**Issue by tiagosteil** [jeffreykemp/jk64-plugin-simplemap#17]
Hi,

First of all I would like to thank you for the plugin and say that it is very good and will be of great help in my project! 

Now we are going to what is happening:

I am using the plugin on a page, with a field for the "Address Item" entered in the properties of the plugin, to be done a Google Maps reverse geocode when the user clicks on some point of the map.

So I added a Dynamic Action with the "address" event to populate the address fields returned by the plugin in separate fields on the screen, the problem is that for some addresses I get the "Insufficient results found" alert in the browser, even the address being found by Google.

So I looked in the google documentation and found the code below in this link https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse and saw that in the geocode function the example shows as follows:

```javascript
if (results [0]) {
              map.setZoom (11);
              var marker = new google.maps.Marker ({
                position: latlng,
                map: map
              });
              infowindow.setContent (results [0] .formatted_address);
              infowindow.open (map, marker);
            } else {
              window.alert ('No results found');
            }
```

Debugging the plugin I saw that the _if_ is done with the test below:

```javascript
if (results [1]) {
$ s (opt.addressItem, results [0] .formatted_address);
        var components = results [0] .address_components;
        for (i = 0; i <components.length; i ++) {
          ("+ components [i] .long_name +") ");" + components [i] .types + "=" + components [i] .short_name + "
        }
        apex.jQuery ("#" + opt.regionId) .trigger ("address", {map: opt.map, result: results [0]});
} else {
window.alert ('Insufficient results found');
}
```

In my case the address is found, however only the record is returned in results [0], there are no results [1]. I also saw that there are more addresses that return less results in the array results.

Now I will leave the map by checking the results [0], I would like to know your opinion.

**Comment by jeffreykemp** [comment]
Hi, thanks very much for raising this.

The reason I check for results[1] is because I found that when there was only one result it didn't seem very useful - at least, for the tests I was running.

I will look further into this when I can and update this issue accordingly.

**Comment by tiagosteil** [comment]
Hi, Thanks for the answer !

I understand. 
For me the results [0] returns all the data of the address that I need. But it's always good to know why.

Thank you!
