### ISSUE TITLE
Oops! Someting went wrong

### ISSUE THREAD

**Issue by JacoFourie** [jeffreykemp/jk64-plugin-simplemap#19]
I have set my Google API Key and when I run the Demo app I get this error

![image](https://user-images.githubusercontent.com/17771641/43631959-01fe5420-9705-11e8-969a-ae9d458889f9.png)

**Comment by jeffreykemp** [comment]
The error message tells you to check the console for errors - what does the console say?

**Comment by JacoFourie** [comment]
OK I see now I had to enable All the API's not just the Maps one. After enabling it all it works now.  I just hope I wont get a huge bill for playing with this as I can not see where to change the API Key to development / Trail only.
